action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"
runner_log_interval: 2500 # how often the agent's are tested and metrics are logged

buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 0

lr: 0.0003

obs_agent_id: False
obs_last_action: True
obs_individual_obs: False

mac: "non_shared_mac"
agent: "th_rnn_ns"
agent_output_type: "pi_logits"
learner: "thesis_learner"
learner_log_interval: 2500
entropy_coef: 0.001
use_rnn: True
standardise_returns: False
standardise_rewards: True
q_nstep: 10 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 10
eps_clip: 0.2
name: "th_mappo_distil_epoch10"

log_interval: 15000
test_interval: 5000
t_max: 500000
use_tensorboard: True
